version: '3.8'

services:
  contabo-snapshot-manager:
    build: .
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 